server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  webservices:
    servlet:
      init-transformWsdlLocations: true
      path: /ws
